### ISSUE TITLE
Question: How long to hold the black screen

### ISSUE THREAD

**Issue by abishur** [arpruss/cwiid-lightgun#1]
I'm trying to learn more about how the light gun operates.  I know when the light gun trigger is pulled the NES first makes the screen black and then lights up the one part of the screen to detect if there was a hit.  If the black screen is not detected by the gun, the NES thinks you're cheating point the gun at a lightbulb or the sun or something.  How long on average have you found that this black screen is help prior to sending the actual light detection status?

**Comment by arpruss** [comment]
I have no idea. I don't have any of the original lightguns. This code is for using a Wiimote with four LEDs around the TV.

**Comment by abishur** [comment]
So with this code, you're hooked up to an emulator, right?  How do you have it translate a hit condition?

**Comment by arpruss** [comment]
That's up to the emulator. The code just emulates an absolute mouse, and then emulators (I use libretro-cored ones) translate that to whatever the particular console needs. You need the latest Retroarch which has better lightgun support.

**Comment by abishur** [comment]
ah, gotcha, thanks!
